#Random number class import
from randomNumber import randomNumber as rand
#GUI import and framework
# from tkinter import *
# from tkinter import ttk
# root = Tk()
# frm = ttk.Frame(root, padding=10)
# frm.grid()
# ttk.Label(frm, text="Hello World!").grid(column=0, row=0)
# ttk.Button(frm, text="Quit", command=root.destroy).grid(column=1, row=0)
# root.mainloop()
#Random number generated by player choice
def number_generator():
    print("Welcome to the number guess game!")
    print("The mystery number is from 0 to infinity! Your choice!")
    while True:
        lower = int(input("Choose the lower bound: "))
        upper = int(input("Choose the upper bound: "))
        if lower < 0:
            print("Sorry, invalid input, lower bound must be greater than zero")
            continue
        elif upper < 0: 
            print("Sorry, invalid input, upper bound must be greater than zero")
            continue
        elif lower > upper:
            print("Sorry, invalid input, lower bound must be less than upper bound")
            continue
        else:
            break
    random_number = rand(lower,upper).random_number()
    return random_number,lower,upper
#Game logic
def num_guess(random_number,lower,upper):
    player_guess = -1
    # print(random_number)
    while True:
        player_guess = int(input(f"Guess the random number in the range of {lower} and {upper}: "))
        if abs(random_number - player_guess) > 10000:
            print("You are further than 10000 from the mystery number")
            continue
        elif abs(random_number - player_guess) > 1000:
            print("You are further than 1000 from the mystery number")
            continue
        elif abs(random_number - player_guess) > 100:
            print("You are further than 100 from the mystery number")
            continue
        elif abs(random_number - player_guess) > 25:
            print("You are further than 25 from the mystery number")
            continue
        elif abs(random_number - player_guess) > 10:
            print("You are further than 10 from the mystery number")
            continue
        elif abs(random_number - player_guess) < 10 and random_number != player_guess:
            print("You are within 10 from the mystery number")
            continue
        elif random_number == player_guess:
            return print(f"Congratulations! You guessed the mystery number of {random_number}")
        
random_number, lower, upper = number_generator()
num_guess(random_number,lower,upper)